apiVersion: v1
kind: Service
metadata:
  name: medusa-service
spec:
  type: LoadBalancer # Use LoadBalancer if supported in your environment.
  selector:
    app: medusa # Make sure this label matches the pods in your Deployment.
  ports:
    - protocol: TCP
      port: 80 # The port that will be exposed by the Service.
      targetPort: 9000 # The port on which your container is listening.
