apiVersion: v1
kind: Secret
metadata:
  name: medusa-secret
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXQ=
  COOKIE_SECRET: c3VwZXJzZWNyZXQ=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlczo1NDMyL21lZHVzYT9zc2xfbW9kZT1kaXNhYmxl
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
